//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("gesperModel", "FK_employe_service", "service", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Linq.service), "employe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Linq.employe), true)]
[assembly: EdmRelationshipAttribute("gesperModel", "posseder", "diplome", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Linq.diplome), "employe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Linq.employe))]

#endregion

namespace Linq
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class gesperEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet gesperEntities à l'aide de la chaîne de connexion trouvée dans la section 'gesperEntities' du fichier de configuration d'application.
        /// </summary>
        public gesperEntities() : base("name=gesperEntities", "gesperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet gesperEntities.
        /// </summary>
        public gesperEntities(string connectionString) : base(connectionString, "gesperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet gesperEntities.
        /// </summary>
        public gesperEntities(EntityConnection connection) : base(connection, "gesperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<diplome> diplomes
        {
            get
            {
                if ((_diplomes == null))
                {
                    _diplomes = base.CreateObjectSet<diplome>("diplomes");
                }
                return _diplomes;
            }
        }
        private ObjectSet<diplome> _diplomes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<employe> employes
        {
            get
            {
                if ((_employes == null))
                {
                    _employes = base.CreateObjectSet<employe>("employes");
                }
                return _employes;
            }
        }
        private ObjectSet<employe> _employes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<service> services
        {
            get
            {
                if ((_services == null))
                {
                    _services = base.CreateObjectSet<service>("services");
                }
                return _services;
            }
        }
        private ObjectSet<service> _services;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet diplomes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTodiplomes(diplome diplome)
        {
            base.AddObject("diplomes", diplome);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet employes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToemployes(employe employe)
        {
            base.AddObject("employes", employe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet services. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToservices(service service)
        {
            base.AddObject("services", service);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gesperModel", Name="diplome")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class diplome : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet diplome.
        /// </summary>
        /// <param name="dip_id">Valeur initiale de la propriété dip_id.</param>
        public static diplome Creatediplome(global::System.Int32 dip_id)
        {
            diplome diplome = new diplome();
            diplome.dip_id = dip_id;
            return diplome;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dip_id
        {
            get
            {
                return _dip_id;
            }
            set
            {
                if (_dip_id != value)
                {
                    Ondip_idChanging(value);
                    ReportPropertyChanging("dip_id");
                    _dip_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dip_id");
                    Ondip_idChanged();
                }
            }
        }
        private global::System.Int32 _dip_id;
        partial void Ondip_idChanging(global::System.Int32 value);
        partial void Ondip_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dip_libelle
        {
            get
            {
                return _dip_libelle;
            }
            set
            {
                Ondip_libelleChanging(value);
                ReportPropertyChanging("dip_libelle");
                _dip_libelle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dip_libelle");
                Ondip_libelleChanged();
            }
        }
        private global::System.String _dip_libelle;
        partial void Ondip_libelleChanging(global::System.String value);
        partial void Ondip_libelleChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("gesperModel", "posseder", "employe")]
        public EntityCollection<employe> employes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<employe>("gesperModel.posseder", "employe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<employe>("gesperModel.posseder", "employe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gesperModel", Name="employe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet employe.
        /// </summary>
        /// <param name="emp_id">Valeur initiale de la propriété emp_id.</param>
        public static employe Createemploye(global::System.Int32 emp_id)
        {
            employe employe = new employe();
            employe.emp_id = emp_id;
            return employe;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_id
        {
            get
            {
                return _emp_id;
            }
            set
            {
                if (_emp_id != value)
                {
                    Onemp_idChanging(value);
                    ReportPropertyChanging("emp_id");
                    _emp_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_id");
                    Onemp_idChanged();
                }
            }
        }
        private global::System.Int32 _emp_id;
        partial void Onemp_idChanging(global::System.Int32 value);
        partial void Onemp_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_nom
        {
            get
            {
                return _emp_nom;
            }
            set
            {
                Onemp_nomChanging(value);
                ReportPropertyChanging("emp_nom");
                _emp_nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_nom");
                Onemp_nomChanged();
            }
        }
        private global::System.String _emp_nom;
        partial void Onemp_nomChanging(global::System.String value);
        partial void Onemp_nomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_prenom
        {
            get
            {
                return _emp_prenom;
            }
            set
            {
                Onemp_prenomChanging(value);
                ReportPropertyChanging("emp_prenom");
                _emp_prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_prenom");
                Onemp_prenomChanged();
            }
        }
        private global::System.String _emp_prenom;
        partial void Onemp_prenomChanging(global::System.String value);
        partial void Onemp_prenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emp_sexe
        {
            get
            {
                return _emp_sexe;
            }
            set
            {
                Onemp_sexeChanging(value);
                ReportPropertyChanging("emp_sexe");
                _emp_sexe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emp_sexe");
                Onemp_sexeChanged();
            }
        }
        private global::System.String _emp_sexe;
        partial void Onemp_sexeChanging(global::System.String value);
        partial void Onemp_sexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> emp_cadre
        {
            get
            {
                return _emp_cadre;
            }
            set
            {
                Onemp_cadreChanging(value);
                ReportPropertyChanging("emp_cadre");
                _emp_cadre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("emp_cadre");
                Onemp_cadreChanged();
            }
        }
        private Nullable<global::System.Boolean> _emp_cadre;
        partial void Onemp_cadreChanging(Nullable<global::System.Boolean> value);
        partial void Onemp_cadreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> emp_salaire
        {
            get
            {
                return _emp_salaire;
            }
            set
            {
                Onemp_salaireChanging(value);
                ReportPropertyChanging("emp_salaire");
                _emp_salaire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("emp_salaire");
                Onemp_salaireChanged();
            }
        }
        private Nullable<global::System.Decimal> _emp_salaire;
        partial void Onemp_salaireChanging(Nullable<global::System.Decimal> value);
        partial void Onemp_salaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> emp_service
        {
            get
            {
                return _emp_service;
            }
            set
            {
                Onemp_serviceChanging(value);
                ReportPropertyChanging("emp_service");
                _emp_service = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("emp_service");
                Onemp_serviceChanged();
            }
        }
        private Nullable<global::System.Int32> _emp_service;
        partial void Onemp_serviceChanging(Nullable<global::System.Int32> value);
        partial void Onemp_serviceChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("gesperModel", "FK_employe_service", "service")]
        public service service
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<service>("gesperModel.FK_employe_service", "service").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<service>("gesperModel.FK_employe_service", "service").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<service> serviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<service>("gesperModel.FK_employe_service", "service");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<service>("gesperModel.FK_employe_service", "service", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("gesperModel", "posseder", "diplome")]
        public EntityCollection<diplome> diplomes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<diplome>("gesperModel.posseder", "diplome");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<diplome>("gesperModel.posseder", "diplome", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="gesperModel", Name="service")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class service : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet service.
        /// </summary>
        /// <param name="ser_id">Valeur initiale de la propriété ser_id.</param>
        public static service Createservice(global::System.Int32 ser_id)
        {
            service service = new service();
            service.ser_id = ser_id;
            return service;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ser_id
        {
            get
            {
                return _ser_id;
            }
            set
            {
                if (_ser_id != value)
                {
                    Onser_idChanging(value);
                    ReportPropertyChanging("ser_id");
                    _ser_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ser_id");
                    Onser_idChanged();
                }
            }
        }
        private global::System.Int32 _ser_id;
        partial void Onser_idChanging(global::System.Int32 value);
        partial void Onser_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ser_designation
        {
            get
            {
                return _ser_designation;
            }
            set
            {
                Onser_designationChanging(value);
                ReportPropertyChanging("ser_designation");
                _ser_designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ser_designation");
                Onser_designationChanged();
            }
        }
        private global::System.String _ser_designation;
        partial void Onser_designationChanging(global::System.String value);
        partial void Onser_designationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ser_type
        {
            get
            {
                return _ser_type;
            }
            set
            {
                Onser_typeChanging(value);
                ReportPropertyChanging("ser_type");
                _ser_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ser_type");
                Onser_typeChanged();
            }
        }
        private global::System.String _ser_type;
        partial void Onser_typeChanging(global::System.String value);
        partial void Onser_typeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ser_produit
        {
            get
            {
                return _ser_produit;
            }
            set
            {
                Onser_produitChanging(value);
                ReportPropertyChanging("ser_produit");
                _ser_produit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ser_produit");
                Onser_produitChanged();
            }
        }
        private global::System.String _ser_produit;
        partial void Onser_produitChanging(global::System.String value);
        partial void Onser_produitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ser_capacite
        {
            get
            {
                return _ser_capacite;
            }
            set
            {
                Onser_capaciteChanging(value);
                ReportPropertyChanging("ser_capacite");
                _ser_capacite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ser_capacite");
                Onser_capaciteChanged();
            }
        }
        private Nullable<global::System.Int32> _ser_capacite;
        partial void Onser_capaciteChanging(Nullable<global::System.Int32> value);
        partial void Onser_capaciteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ser_budget
        {
            get
            {
                return _ser_budget;
            }
            set
            {
                Onser_budgetChanging(value);
                ReportPropertyChanging("ser_budget");
                _ser_budget = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ser_budget");
                Onser_budgetChanged();
            }
        }
        private Nullable<global::System.Decimal> _ser_budget;
        partial void Onser_budgetChanging(Nullable<global::System.Decimal> value);
        partial void Onser_budgetChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("gesperModel", "FK_employe_service", "employe")]
        public EntityCollection<employe> employes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<employe>("gesperModel.FK_employe_service", "employe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<employe>("gesperModel.FK_employe_service", "employe", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
